############################################################
# +------------------------------------------------------+ #
# |                 Глобальные настройки                 | #
# +------------------------------------------------------+ #
############################################################

#Показывать название города
showCity: true

#Показывать название страны
showCountry: true

#Показывать название области (штата и т.д.)
showStats: false

#Показывать название континета (Европа, Северная америка и т.д)
showContinent: false

#Язык, на котором будут выводится названия (см. раздел "Список доступных языков" ниже)
language: 'en'



############################################################
# +------------------------------------------------------+ #
# |               Список доступных языков                | #
# +------------------------------------------------------+ #
############################################################

# Обозначение для 'language' | Название
# de     | Немецкий
# en     | Английский 
# es     | Испанский
# fr     | Французский
# ja     | Японский
# pt-BR  | Португальский
# ru     | Русский
# zh-CN  | Китайский


############################################################
# +------------------------------------------------------+ #
# |                 Настройки сообщений                  | #
# +------------------------------------------------------+ #
############################################################
GeoPlayer:
  Player: '§6====== Игрок: §c{player}§6 ======'
  IP: '§6- IP: §c'
  Continent: '§6- Часть света: §c'
  Country: '§6- Страна: §c'
  Subdivisions: '§6- Субъект: §c'
  City: '§6- Город: §c'

GeoIP:
  IP: '§6====== IP: §c{ip}§6 ======'
  Continent: '§6- Часть света: §c'
  Country: '§6- Страна: §c'
  Subdivisions: '§6- Субъект: §c'
  City: '§6- Город: §c'
  
PlayerOffline: '§4[Ошибка] §cИгрок с таким ником не найдет!'
  
#// 1.0 UPDATES:
Modules:
  GeoWhois:
    Header: '§6====== WhoIs: §c{name} §6======'
    Nick: '§6- Ник: §c'
    Health: '§6- Здоровье: §c{0}§6/20'
    Hunger: '§6- Голод: §c{0}§6/20 (+§c{1}§6 насыщение)'
    Exp: '§6- Опыт: §c{0}§6 (уровень §c{1}§6)'
    Location: '§6- Местоположение: (§c{world}§6)'
    IP: '§6- IP адрес: §c'
    GeoLocation: '§6- Местоположение: §c'
    GameMode: '§6- Игровой режим: §c'
    God: '§6- Режим Бога: §c'
    OP: '§6- OP: §c'
    FLY: '§6- Режим полета: §c{0}§6 (§c{1}§6)'
    AFK: '§6- AFK: §c'
    Jail: '§6- В тюрьме: §c'
    Mute: '§6- В муте: §c'
    string_true: '§aистина'
    string_false: '§cложь'
    not_flying: 'не летает'
    flying: 'летает'
    year: 'год'
    mouth: 'мес.'
    day: 'дн.'
    hour: 'ч.'
    minute: 'мин.'
    second: 'сек.'

creative: 'творческий'
survival: 'выживание'
adventure: 'приключение'
spectator: 'наблюдатель'